---
title: Waze India Community
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@wazeindia.in
url: https://wazeindia.in
description: Waze India Community
skills: Outsmarting traffic, together
google_verify: 
bing_verify: 
contact: static
color:
  primary: 93c4d1
  primary-rgb: '147,196,209'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: 'Disclaimer: This website and linked pages are managed by the Waze India
    Community, and not operated or supervised by Waze.'
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: https://twitter.com/wazeindia
- title: facebook
  url: https://www.facebook.com/WazeIndia/
address:
- line: India
credits: 'With many thanks to <a href="https://www.waze.com/user/editor/gertbroos">Gert</a>,
  <a href="https://www.waze.com/user/editor/petervdveen">Peter</a>, <a href="https://www.waze.com/user/editor/jlsjonas">Jonas</a>
  and <a href="https://www.waze.com/user/editor/didierlmn">Didier</a> '
markdown: kramdown
permalink: pretty
